questions =  [
    {"id": 0, "question": "Abortion should be protected as a human right", "effects": {"prog": 1}},
    {"id": 1, "question": "Marriage is between a man and a woman", "effects": {"prog": -1}},
    {"id": 2, "question": "First Nations deserve more autonomy in Canada", "effects": {"prog": 1}},
    {"id": 3, "question": "The consumption/trafficking/sale of illicit drugs should be forbidden", "effects": {"prog": -0.5}},
    {"id": 4, "question": "The idea that Canada is multicultural nation is a disaster", "effects": {"prog": -1.5}},
    {"id": 5, "question": "The Monarchy as an institution in Canada should be abolished", "effects": {"prog": 1.5}},
    {"id": 6, "question": "Transgender individuals deserve to have their preferred gender and pronouns officially recognized", "effects": {"prog": 1}},
    {"id": 7, "question": "Systemic racism is a real issue in Canada and needs to be resolved", "effects": {"prog": 1}},
    {"id": 8, "question": "The Canadian National Anthem is outdated and needs to be replaced", "effects": {"prog": 0.5}},
    {"id": 9, "question": "Conversion therapy is immoral and dangerous", "effects": {"prog": -1}},
    {"id": 10, "question": "Universal Healthcare has been a failure in our country" "effects": {"right": 1}},
    {"id": 11, "question": "Land should not be a commodity to be bought and sold.", "effects": {"right": -1}},
    {"id": 12, "question": "Free trade only hurts our country and we deserve more control over our trading operations", "effects": {"right": -1}},
    {"id": 13, "question": "There’s no such thing as private property", "effects": {"right": -1}},
    {"id": 14, "question": "The rich deserve to be taxed at a greater rate", "effects": {"right": -1}},
    {"id": 15, "question": "Decentralized forms of finance such as cryptocurrencies should be regulated or banned", "effects": {"right": -1}},
    {"id": 16, "question": "Our financial system is too centralized and is heavily influenced by a small group of people", "effects": {"right": 1}},
    {"id": 17, "question": "Austerity measures can be acceptable in certain conditions", "effects": {"right": -0.5}},
    {"id": 18, "question": "Dental care should be covered in Healthcare", "effects": {"right": -0.5}},
    {"id": 19, "question": "Fiat money has been a disaster and we must return to the gold standard or another more free market alternatives", "effects": {"right": 1.5}},
    {"id": 20, "question": "The government has the right to confiscate property", "effects": {"auth": 1}},
    {"id": 21, "question": "The Canadian Government is morally in the right by spying on civilians to protect the nation's security", "effects": {"auth": 1}},
    {"id": 22, "question": "Canada should turn away from federalism and turn into a unitary, centralized state", "effects": {"auth": 1}},
    {"id": 23, "question": "There needs to be a government mandate to restrict certain dangerous types of speeches and opinions", "effects": {"auth": 1}},
    {"id": 24, "question": "The government has no right to restrict the possession of firearms", "effects": {"auth": -1}},
    {"id": 25, "question": "In times of war, the government has the right to conscript citizens to defend the nation", "effects": {"auth": 1}},
    {"id": 26, "question": "The government has the right to confiscate electronic devices for legal inspection", "effects": {"auth": 1}},
    {"id": 27, "question": "In times of severe crisis and unrest, the government has the responsibility to restrict liberty in the name of security", "effects": {"auth": 1}},
    {"id": 28, "question": "The government needs to suppress false misinformation to protect the nation's interest", "effects": {"auth": 1}},
    {"id": 29, "question": "Making vaccines compulsory is not just moral but a no brainer", "effects": {"auth": 1}},
];
